title: Development Solutions Organization
baseURL: /
disqusShortname: dsoglobal
googleAnalytics: UA-45279912-1
params:
  accent_color: blue
  color_scheme: light
  footer:
    content: '&copy; Development Solutions Organization. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    logo_img: /images/logo-2-.png
    title: DSO
taxonomies:
  category: categories
  tag: tags
