[build]
publish = "public"
command = "./stackbit-build.sh"

  [build.environment]
  HUGO_VERSION = "0.47"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  
[[plugins]]
  package = "netlify-plugin-algolia-index"

[[plugins]]
package = "netlify-plugin-checklinks"
